<?php

namespace ContainerGGULqdn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetiton2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lV5dZ0Y.App\Entity\Competiton' shared service.
     *
     * @return \App\Entity\Competiton
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lV5dZ0Y": it references class "App\\Entity\\Competiton" but no such service exists.');
    }
}
