<?php

namespace ContainerODKtuxH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneralUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cgcr7.b.App\Entity\GeneralUser' shared service.
     *
     * @return \App\Entity\GeneralUser
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cgcr7.b": it references class "App\\Entity\\GeneralUser" but no such service exists.');
    }
}
