<?php

namespace ContainerOFzpFtc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEquipe2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bPe7bSN.App\Entity\Equipe' shared service.
     *
     * @return \App\Entity\Equipe
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bPe7bSN": it references class "App\\Entity\\Equipe" but no such service exists.');
    }
}
