<?php

namespace ContainerZ0nCBbS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AiaugixService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Aiaugix' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Aiaugix'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'equipes' => ['privates', 'App\\Repository\\EquipeRepository', 'getEquipeRepositoryService', true],
        ], [
            'equipes' => 'App\\Repository\\EquipeRepository',
        ]);
    }
}
