<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQRZFWkP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQRZFWkP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQRZFWkP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQRZFWkP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQRZFWkP\App_KernelDevDebugContainer([
    'container.build_hash' => 'QRZFWkP',
    'container.build_id' => '4f05bf40',
    'container.build_time' => 1614673666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQRZFWkP');
