<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4ChetGY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4ChetGY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4ChetGY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4ChetGY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4ChetGY\App_KernelDevDebugContainer([
    'container.build_hash' => '4ChetGY',
    'container.build_id' => '1939a8c5',
    'container.build_time' => 1614679287,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4ChetGY');
